@echo off
setlocal EnableDelayedExpansion
title Synapic Launcher
color 0A

:: Ensure we're running from the script's own directory
pushd "%~dp0" || (
    echo [ERROR] Could not change to script directory.
    pause
    exit /b 1
)

echo ===============================================================================
echo                                SYNAPIC LAUNCHER                                
echo ===============================================================================
echo.

:: 0. Check/Download Repository
if not exist "main.py" (
    echo [!] Synapic core files make sure 'main.py' is in the folder.
    echo [*] If this is a new installation, we can download the latest version.
    echo.
    echo Press any key to download Synapic from GitHub...
    pause >nul
    
    echo [*] Downloading latest code from https://github.com/deanable/Synapic...
    powershell -Command "Invoke-WebRequest -Uri 'https://github.com/deanable/Synapic/archive/refs/heads/main.zip' -OutFile 'synapic.zip'"
    
    if exist "synapic.zip" (
        echo [*] Extracting repository...
        powershell -Command "Expand-Archive -Path 'synapic.zip' -DestinationPath '.'"
        if !errorlevel! neq 0 (
            echo [ERROR] Failed to extract 'synapic.zip'. The file might be corrupted.
            del "synapic.zip"
            pause
            exit /b 1
        )

        if exist "Synapic-main" (
            echo [*] Moving files to root...
            :: Use robocopy to move and exclude this script to prevent self-overwrite issues
            :: generated by system: excluding start_synapic.bat to avoid crashing the running script
            robocopy "Synapic-main" "." /E /IS /MOVE /XF "start_synapic.bat" >nul
            if !errorlevel! geq 8 (
                echo [!] Error during file move. Cleanup skipped.
            ) else (
                rmdir /S /Q "Synapic-main"
                del "synapic.zip"
                echo [V] Download and setup complete.
            )
        ) else (
            echo [!] Failed to confirm extracted folder. structure might have changed.
            pause
            exit /b 1
        )
    ) else (
        echo [ERROR] Failed to download 'synapic.zip'. Check internet connection.
        pause
        exit /b 1
    )
    echo.
)

:: 1. Check for Python
echo [*] Checking for Python installation...
where python >nul 2>&1
if %errorlevel% neq 0 (
    echo [!] Python is NOT found. Attempting to install...
    
    :: Check if winget is available
    where winget >nul 2>&1
    if !errorlevel! neq 0 (
        color 0C
        echo [ERROR] Winget is not available to auto-install Python.
        echo Please install Python manually from https://www.python.org/
        pause
        exit /b 1
    )

    echo [*] Installing Python via Winget...
    winget install -e --id Python.Python.3 --source winget --accept-package-agreements --accept-source-agreements
    
    if !errorlevel! neq 0 (
        color 0C
        echo [ERROR] Automatic installation failed.
        echo Please install Python manually from https://www.python.org/
        pause
        exit /b 1
    )

    echo [*] Python installed.
    echo [!] IMPORTANT: You must restart this script to complete the setup.
    pause
    exit /b 0
) else (
    echo [V] Python is installed:
    python --version
)

echo.
echo ===============================================================================
echo                          SETTING UP ENVIRONMENT                                
echo ===============================================================================
echo.

:: 2. Setup/Check Virtual Environment
if not exist ".venv" (
    echo [*] Creating virtual environment .venv...
    python -m venv .venv
    if !errorlevel! neq 0 (
        echo [!] Failed to create venv. Will attempt to use system Python...
    ) else (
        echo [V] Virtual environment created.
    )
)

if exist ".venv" (
    echo [*] Activating virtual environment...
    if exist ".venv\Scripts\activate.bat" (
        call .venv\Scripts\activate.bat
        echo [V] Virtual environment activated.
    ) else (
        echo [!] .venv folder exists but activate.bat not found. Using system Python.
    )
)

:: 3. Install Requirements
echo.
echo [*] Checking dependencies...
if exist "requirements.txt" (
    echo [*] Installing/Updating requirements...
    pip install -r requirements.txt
    if !errorlevel! neq 0 (
        color 0C
        echo.
        echo [ERROR] Failed to install dependencies.
        echo Please check your internet connection or requirements.txt file.
        pause
        exit /b 1
    )
    echo [V] Dependencies installed/updated.
) else (
    echo [!] requirements.txt not found! Skipping dependency installation.
)

echo.
echo ===============================================================================
echo                               LAUNCHING APP                                    
echo ===============================================================================
echo.

:: 4. Launch Main (windowless — no console will appear)
if exist "main.py" (
    echo [*] Launching Synapic...
    :: Prefer pythonw.exe from the venv (suppresses console window).
    :: Fall back to the system pythonw if the venv one is missing.
    :: Launch detached so the launcher window can close once the GUI is up.
    if exist ".venv\Scripts\pythonw.exe" (
        start /b "" .venv\Scripts\pythonw.exe "main.py"
    ) else (
        start /b "" pythonw "main.py"
    )
    echo [*] Application launched. Closing launcher window...
    timeout /t 2 /nobreak >nul
) else (
    color 0C
    echo [ERROR] main.py not found in current directory!
    pause
    exit /b 1
)

popd
endlocal
exit
